church/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scripture.urls'))
]

scripture/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_index, name='index'),
    path('register', views.view_register, name='register'),
    path('login', views.view_login, name='login'),
    path('logout', views.view_logout, name='logout'),
    path('search', views.view_search, name='search'),
    path('guide', views.view_guide, name='guide'),
    path('mysettings', views.view_mysettings, name='mysettings'),
    path('retrieve-password', views.view_retrieve_password, name='retrieve-password'),
    path('reset-password', views.view_reset_password, name='reset-password'),
    path('verify', views.verify_new_user),
    path('userprofile', views.view_userprofile, name='userprofile'),
    

    path('books', views.view_books, name='books'),
    path('books/<int:id>', views.view_book, name='book'),

    path('characters', views.view_characters, name='characters'),
    path('characters/<int:id>', views.view_character, name='character'),

    path('places', views.view_places, name='places'),
    path('places/<int:id>', views.view_place, name='place'),

    path('blogs', views.view_blogs, name='blogs'),
    path('blogs/<int:id>', views.view_blog, name='blog'),
    path('blog-add', views.view_blog_add, name='blog-add'),
    path('blog-edit/<int:id>', views.view_blog_edit, name='blog-edit'),
    path('blog-del/<int:id>', views.view_blog_del, name='blog-del'),
    path('myblogs', views.view_my_blogs, name='my-blogs'),
    path('filtered-blogs', views.view_filter_blogs, name='filtered-blogs'),

    # API End Points
    path('setLocation', views.view_setLocation, name='setLocation'),
    path('getUserState', views.view_getUserState, name='getUserState'),
    path('getCurrentLocation', views.view_getCurrentLocation, name='getCurrentLocation'),
    path('addVerseToFavorites', views.view_addVerseToFavorites, name='addVerseToFavorites'),
    path('getFavVersesIdForUser', views.view_getFavVersesIdForUser, name='getFavVersesIdForUser'),
    path('getFavVersesForUser', views.view_getFavVersesForUser, name='getFavVersesForUser'),
    path('removeVerseFromFav/<int:id>', views.view_removeVerseFromFav, name='removeVerseFromFav'),
]

scripture/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.deletion import CASCADE
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator

# Scripture models.

class User(AbstractUser):
    country = models.ForeignKey('Country', null=True, on_delete=models.SET_NULL)
    mobile = models.CharField(max_length=22, null=True)
    gender = models.CharField(max_length=7, null=True)
    birthdate = models.DateField(null=True)
    location = models.OneToOneField('Verse', null=True, on_delete=models.RESTRICT)
    fav_verses = models.ManyToManyField('Verse', related_name='users_like')


class Country(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=7)
    iso = models.CharField(max_length=3)
    title = models.CharField(max_length=100)


class Identity(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Character(models.Model):
    name = models.CharField(max_length=50)
    nickname = models.CharField(max_length=50)
    fullname = models.TextField()
    gender = models.CharField(max_length=10)
    age = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(969)])
    about = models.TextField()
    identity = models.ManyToManyField(Identity)
    is_writter = models.BooleanField()

    def __str__(self) -> str:
        return f"{self.name}"


class BooKMeta(models.Model):
    written_from = models.DateField(auto_now=False, auto_now_add=False)
    written_to = models.DateField(auto_now=False, auto_now_add=False)
    written_in = models.CharField(max_length=255)
    written_by = models.ManyToManyField(Character)
    about = models.TextField(null=True)


class Book(models.Model):
    name = models.CharField(max_length=30)
    number = models.IntegerField()
    symbol = models.CharField(max_length=3)
    title = models.CharField(max_length=33)
    titlelong = models.CharField(max_length=99)
    book_about = models.TextField(null=True)
    book_meta = models.OneToOneField(BooKMeta, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"({self.number}) {self.name}"


class Chapter(models.Model):
    number = models.IntegerField()
    title = models.CharField(max_length=55)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.book.name} ({self.number})"


class Verse(models.Model):
    number = models.IntegerField()
    text = models.TextField()
    textf = models.TextField()
    textq = models.TextField()
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)

    def __str__(self):
        return f"({self.number}) {self.textf}"


class Blog(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    for_publish = models.BooleanField()
    reviewed = models.BooleanField()
    written_by = models.ForeignKey(User, on_delete=models.CASCADE)
    last_edited = models.DateTimeField(auto_now=True)

scripture/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password, make_password
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.db.models import Q
from .models import Blog, Book, Chapter, User, Verse, Country
from django.views.decorators.csrf import csrf_exempt
import json
import functools
import datetime
import string
import random
import smtplib
import jwt


# APP VIEWS.
def view_index(request):
    books = Book.objects.all()
    return render(request, "scripture/index.html", {
        "books": books
    })


def view_main(request):
    return render(request, "scripture/main.html")

def view_guide(request):
    return render(request, "scripture/guide.html")


def view_login(request):
    if request.method == 'POST':
        # Login the user
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("blogs"))
        else:
            return render(request, "scripture/login.html", {
                "errorMessage": "رجاء التأكد من أسم المستخدم وكلمة المرور، وإعاده المحاولة"
            })

    else:
        return render(request, "scripture/login.html")


def view_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def view_register(request):
    countries = Country.objects.all().order_by('title')

    # Receive data from the post request and assign it into variables
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('e_mail')
        mobile = request.POST.get('mobile')
        country_id = request.POST.get('country')
        first_name = request.POST.get('firstName')
        last_name = request.POST.get('lastName')
        birthdate = request.POST.get('birthdate')
        password = request.POST.get('password')
        confirm = request.POST.get('confirm')
        sex = request.POST.get('sex')

        # Validating received inputs
        if ((not username) or (not email) or (not first_name) or (not last_name) or (not password) or (not confirm)):
            return render(request, "scripture/register.html", {
                "countries": countries,
                "errorMessage": "برجاء ملئ كافة الحقول التى تنتهى بالعلامة (*) لانها ضرورية لانشاء الحساب"
            })

        registered_users = User.objects.filter(
            Q(username=username) | Q(email=email) | Q(mobile=mobile)).count()
        print("The Total count", registered_users)
        if registered_users > 0:
            return render(request, "scripture/register.html", {
                "countries": countries,
                "errorMessage": "هذا المستخدم مسجل بالفعل، من فضلك أستخدام (أسم - بريد - موبيل) أخر!"
            })

        if (password != confirm):
            return render(request, "scripture/register.html", {
                "countries": countries,
                "errorMessage": "رجاء التأكد من توافق كلمة المرور مع حقل التاكيد!"
            })

        # Register New User
        country = Country.objects.get(id=country_id)

        user = User(
            username=username,
            email=email,
            country=country,
            mobile=mobile,
            first_name=first_name,
            last_name=last_name,
            birthdate=birthdate,
            is_active=False,
            password=make_password(password),
            gender=sex
        )
        user.save()

        # Creating access jwt token
        encoded_jwt = jwt.encode({"id": user.id, "email": user.email, "mobile":user.mobile}, "THE LORD IS MY PROVIDER", algorithm="HS256")

        # Sending the activation link by mail
        gmail_user = 'appmsr7@gmail.com'
        gmail_password = '4get@web'

        # try:
        to = [user.email]
        print(to)
        subject = 'Super Important Message'
        body = f'open the link to activate your account: https://msr.church/verify?t={encoded_jwt}'

        email_text = """\
        From: %s
        To: %s
        Subject: %s

        %s
        """ % (gmail_user, ", ".join(to), subject, body)

        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.ehlo()
        server.login(gmail_user, gmail_password)
        server.sendmail(gmail_user, to, email_text)
        server.close()
        print('MAIL SENT!')


        # Login registered user and redirect him to the index page
        return render(request, "scripture/shortMessage.html", {
        "shortMessage": f"تم إنشاء الحساب، برجاء الدخول على البريد الإلكتروني الذ تم التسجيل به ({user.email}) والضغط على الرابط بالرسالة الوردة من فريق إدارة الموقع (appmsr7@gmail.com) لتفعيل الحساب، ثم الدخول بأستخدام أسم المستخدم وكلمة المرور الخاصة بكم."
    })

    else:
        return render(request, "scripture/register.html", {
            "countries": countries
        })


def verify_new_user(request):
    encoded_jwt = request.GET.get('t')
    decoded_jwt = jwt.decode(encoded_jwt, "THE LORD IS MY PROVIDER", algorithms=["HS256"])
    user = User.objects.get(pk=decoded_jwt['id'])
    user.is_active = True
    user.save()

    return HttpResponseRedirect(reverse('login'))
        

def view_reset_password(request):
    if request.method == 'POST':
        # Extracting data from the request
        oldPassword = request.POST.get("old_password")
        newPassword = request.POST.get("new_password")
        confirmPassword = request.POST.get("confirm_password")

        # Getting old password from db
        c_user = request.user
        user_old_password = c_user.password

        # Hashing the old password received in the request
        matchcheck = check_password(oldPassword, user_old_password)

        # Validating the old and new passwords
        if matchcheck and (newPassword == confirmPassword):
            print(newPassword)
            c_user.password = make_password(newPassword)
            c_user.save()
            return(HttpResponseRedirect(reverse('index')))

        print('password not match')
        return render(request, "scripture/resetPassword.html", {"errorMessage": "رجاء التأكد من صحة البيانات المدخلة، وإعادة المحاولة"})

    else:
        return render(request, "scripture/resetPassword.html")


def view_retrieve_password(request):
    if request.method == 'POST':
        user_username = request.POST.get('username')
        user_email = request.POST.get('email')
        user_mobile = request.POST.get('mobile')
        # get random password pf length 8 with letters, digits, and symbols
        # characters = string.ascii_letters + string.digits + string.punctuation
        characters = string.ascii_letters + string.digits
        temp_password = ''.join(random.choice(characters) for i in range(8))
        print(temp_password)

        # Save the temp password in the db
        user = User.objects.filter(email=user_email).first()
        
        if not user:
            return render(request, "scripture/retrievepassword.html", {
                "errorMessage": "رجاء التأكد من صحة البيانات المدخلة، وإعادة المحاولة"
            })
        
        if user_username == user.username and user_mobile == user.mobile:
            user.password = make_password(temp_password)
            user.save()
        else:
            return render(request, "scripture/retrievepassword.html", {
                "errorMessage": "رجاء التأكد من صحة البيانات المدخلة، وإعادة المحاولة"
            })

        # Send Mail to reset passwords
        gmail_user = 'appmsr7@gmail.com'
        gmail_password = '4get@web'

        try:
            to = [user_email]
            subject = 'Super Important Message'
            # body = u'كلمة المرور المؤقتة هي: ({temp_password}) \n برجاء إعادة تعيين كلمة المرور بعد الدخول على الحساب، شكراً!'
            body = f'Your temp password: {temp_password}'

            email_text = """\
            From: %s
            To: %s
            Subject: %s

            %s
            """ % (gmail_user, ", ".join(to), subject, body)

            server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
            server.ehlo()
            server.login(gmail_user, gmail_password)
            server.sendmail(gmail_user, to, email_text)
            server.close()
            print('MAIL SENT!')

        except:
            return render(request, "scripture/shortMessage.html", {
            "shortMessage": "حدث خطأ! من فضلك أعد المحاولة"
            })

        return render(request, "scripture/shortMessage.html", {
            "shortMessage": f"تم إرسال كلمة مرور جديدة على البريد الالكتروني الخاص بك ({user.email})"
        })

    else:
        return render(request, "scripture/retrievepassword.html")


def view_userprofile(request):
    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('e_mail')
        mobile = request.POST.get('mobile')
        country_id = request.POST.get('country')
        first_name = request.POST.get('firstName')
        last_name = request.POST.get('lastName')
        birthdate = request.POST.get('birthdate')
        sex = request.POST.get('sex')

        # Validation
        if User.objects.exclude(pk=request.user.id).filter(username=username).count() > 0:
            return render(request, "scripture/userprofile.html", {
                "errorMessage": "هذا الاسم مستخدم بالفعل، من فضلك أختر أسم أخر أو أضف بعض الارقام للاسم"
            })

        # Get the selected country
        country = Country.objects.get(pk=int(country_id))

        # Update user profile data
        user = request.user
        user.username = username
        user.email = email
        user.mobile = mobile
        user.country = country

scripture/templates/scripture/blog.html
{% extends 'scripture/layout.html' %}
{% load static %}
{% load scripture_extras %}

{% block content %}
<div id="id_blog-add__title">
    <h1 class="text-center shadow-lg p-3 mb-5 bg-body rounded">
        <span style="float:right">
            <a href="/blogs">
                <img src="{% static 'scripture/img/right-arrow.png' %}" alt="Home" style="width: 2rem;">
            </a>
        </span>
        {{blog.title}}
    </h1>
</div>
<div id="id_blog__paragraph">
    <p class="cc_blog__paragraph">{{blog.content|linebreaks}}</p>
</div>

{% endblock %}

scripture/templates/scripture/blogadd.html
{% extends 'scripture/layout.html' %}
{% load static %}
{% load scripture_extras %}

{% block content %}
<div id="id_blog-add__title">
    <h1 class="text-center shadow-lg p-3 mb-5 bg-body rounded">
        <span style="float:right">
            <a href="/blogs">
                <img src="{% static 'scripture/img/right-arrow.png' %}" alt="Home" style="width: 2rem;">
            </a>
        </span>
        اضافة منشور
    </h1>
</div>

<div id="id_blog-add__cont">
    <form action="{%url 'blog-add' %}" method="POST">
        {% csrf_token %}

        <div class="mb-3">
            <label for="formControlTitle" class="form-label">عنوان المنشور</label>
            <input type="text" class="form-control" id="formControlTitle" name="title">
        </div>
        <div class="mb-3">
            <label for="formControlContent" class="form-label">محتوى المنشور</label>
            <textarea class="form-control" id="formControlContent" rows="12" name="content"></textarea>
        </div>
        <div id="usernameHelp" class="form-text">عند الضغط على (حفظ) سيتم حفظ المنشور بسجل المنشورات الخاص بك. إن كنت تريد
            مشاركته مع جميع المستخدمين، يمكنك تحديد (للنشر) وسيتم مراجعة المنشور أولا من جانب فريق إدارة المحتوى ونشرة
            فى
            اقرب وقت.. خالص التقدير لمشاركتكم!</div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="PUB" id="flexCheckpublish" name="publish">
            <label class="form-check-label" for="flexCheckpublish">
                للنشر
            </label>
        </div>

        <button type="submit" class="btn btn-success cc_input-label mt-4">
            حفظ&nbsp&nbsp&nbsp&nbsp
            <img src="{% static 'scripture/img/add_w.png' %}" alt="Login" style="width: 2rem;"/>
          </button>
    </form>
</div>

{% endblock %}

scripture/templates/scripture/books.html
{% extends 'scripture/layout.html' %}
{% load static %}
{% load scripture_extras %}



{% block content %}
<div id="id_books__title">
    <h1 class="text-center shadow-lg p-3 mb-5 bg-body rounded">أسفار الكتاب المقدس</h1>
</div>

<div id="id_books__tbl">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">السفر</th>
                <th scope="col" class="browser-only">عدد الاصحاحات</th>
                <th scope="col" class="browser-only">الاختصار</th>
                <th scope="col" class="text-end browser-only">En Title</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
            <tr>
                <th scope="row">{{ book.id|arnum }}</th>
                <td>
                    <a class="cc_book-title__link" href="{% url 'book' book.id %}">{{ book.titlelong }}</a>
                </td>
                <td class="browser-only">{{ book.chapter_set.count|arnum }}</td>
                <td class="browser-only">{{ book.symbol }}</td>
                <td class="text-end browser-only">
                    <a class="cc_book-title__link" href="{% url 'book' book.id %}">{{ book.name|title }}</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

scripture/templates/scripture/character.html
{% extends 'scripture/layout.html' %}
{% load static %}



{% block content %}
    
{% endblock %}

scripture/templates/scripture/characters.html
{% extends 'scripture/layout.html' %}
{% load static %}



{% block content %}
    <div id="id_books__title">
        <h1 class="text-center shadow-lg p-3 mb-5 bg-body rounded">شخصيات الكتاب المقدس</h1>
    </div>

    <div id="id_under-construction__perview">
        <img src="{% static 'scripture/img/under_construction.jpeg' %}" alt="Under Construction, COMMING SOON!">
    </div>
    <div id="id_under-construction__txt">
        <h4>Under Construction</h4>
        <h3>COMMING SOON</h3>
    </div>
{% endblock %}
    

scripture/templates/scripture/favVerses.html
{% extends 'scripture/layout.html' %}
{% load static %}
{% load scripture_extras %}

{% block content %}
<div id="id_books__title">
    <h1 class="text-right shadow-lg p-3 mb-5 bg-body rounded">
        قائمة الأعداد المفضلة:
    </h1>
</div>

<div id="id_fav-verses__perview">
    {% if verses %}
    <ul>
        {% for verse in verses %}
        <li>
            <div>
                <a href="{% url 'book' verse.chapter.book.id %}?verse={{verse.id}}#chapter-{{verse.chapter.id}}"
                    target="_blank" class="cc_verse__link">
                    <p>
                        <span style="white-space: nowrap">
                            [{{forloop.counter|arnum}}]
                        </span>
                        {{verse.textf}}
                        <span style="white-space: nowrap">
                            ({{verse.chapter.book.title}} {{verse.chapter.number|arnum}} : {{verse.number|arnum}})
                        </span>
                    </p>
                </a>
            </div>
            <div>
                <a class="btn btn-danger" href="{% url 'removeVerseFromFav' verse.id %}">X</a>
            </div>

        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>لا يوجد أى أعداد بالقائمة!</p>
    {% endif %}
</div>
{% endblock %}

scripture/templates/scripture/guide.html
{% extends 'scripture/layout.html' %}
{% load static %}


{% block content %}
<div id="id_books__title">
  <h1 class="text-center shadow-lg p-3 mb-5 bg-body rounded">دليل استخدام الموقع</h1>
</div>

<div id="id_under-construction__perview">
  <img src="{% static 'scripture/img/under_construction.jpeg' %}" alt="Under Construction, COMMING SOON!">
</div>
<div id="id_under-construction__txt">
  <h4>Under Construction</h4>
  <h3>COMMING SOON</h3>
</div>
{% endblock %}
  

scripture/templates/scripture/index.html
{% extends 'scripture/layout.html' %}
{% load static %}
{% load scripture_extras %}



{% block content %}
<div id="id_index__area" class="row row-cols-1 row-cols-md-3 g-4">
    {% for book in books %}

    <div class="col">
        <div class="card h-100">
            {% with book.name|add:".jpg" as imgname %}
            <img style="height: 15rem; object-fit: cover;" src="{% static 'scripture/img/bookcovers/'|add:imgname %}" class="card-img-top" alt="{{book.title}}">
            {% endwith %}
            <div class="card-body">
                <h5 class="card-title">{{book.titlelong}}</h5>
                <p class="card-text">{{book.book_about}}</p>
                <a class="btn btn-success" href="{% url 'book' book.id %}">
                    الدخول الى السفر&nbsp&nbsp
                    <img src="{% static 'scripture/img/left-arrow_w.png' %}" alt="Home" style="width: 2rem;">
                </a>
            </div>
        </div>
    </div>

    {% endfor %}
</div>

{% endblock %}

scripture/templates/scripture/login.html
{% extends 'scripture/layout.html' %}
{% load static %}

{% block content %}

{% if errorMessage %}
  <div class="alert alert-danger" role="alert">
    {{ errorMessage }}
  </div>
{% endif %}

<form id="login__form" action="{% url 'login' %}" method="post">
  {% csrf_token %}
  <div class="mb-3">
    <label for="id_username__input" class="form-label cc_input-label">أسم المستخدم</label>
    <input
      type="text"
      class="form-control cc_input-control text-center"
      id="id_username__input"
      name="username"
    />
  </div>

  <div class="mb-3">
    <label for="id_password__input" class="form-label cc_input-label">كلمة المرور</label>
    <input
      type="password"
      id="id_password__input"
      class="form-control cc_input-control text-center"
      aria-describedby="passwordHelpBlock"
      name="password"
    />
    <div id="passwordHelpBlock" class="form-text">
      <!-- Your password must be 8-20 characters long, contain letters and numbers,
      and must not contain spaces, special characters, or emoji. -->
    </div>
  </div>

  <p class="cc_note-paragraph">
    ليس لديكم حساب؟ ... يمكنكم انشاء حساب
    <span><a href="{% url 'register' %}">من هنا</a></span>
  </p>
  <p class="cc_note-paragraph">
    نسيت كلمة المرور؟ ... يمكنكم أستعادتها
    <span><a href="{% url 'retrieve-password' %}">من هنا</a></span>
  </p>

  <button type="submit" class="btn btn-success cc_input-label">
    دخول&nbsp&nbsp&nbsp&nbsp
    <img
      src="{% static 'scripture/img/log-in-w.png' %}"
      alt="Login"
      style="width: 2rem"
    />
  </button>
</form>

{% endblock %}

scripture/templates/scripture/place.html
{% extends 'scripture/layout.html' %}
{% load static %}



{% block content %}
    
{% endblock %}

scripture/templates/scripture/register.html
{% extends 'scripture/layout.html' %}
{% load static %}


{% block content %}

{% if errorMessage %}
  <div class="alert alert-danger" role="alert">
    {{ errorMessage }}
  </div>
{% endif %}

<form id="registeration-form" action="{%url 'register' %}" method="POST">

  {% csrf_token %}
  
  <div class="mb-3">
    <input type="text" class="form-control cc_input-control" id="id_username"
      aria-describedby="usernameHelp" placeholder="اسم المستخدم*" name="username">
    <div id="usernameHelp" class="form-text">لتسجيل الدخول، يفضل ان يكون باللغة الانجليزية، ويجب عليك عدم الافصاح به!</div>
  </div>

  <div class="mb-3">
    <input type="email" class="form-control cc_input-control text-center" id="id_email"
      aria-describedby="emailHelp" placeholder="*البريد الالكتروني" name="e_mail">
    <!-- <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
  </div>

  <div class="mb-3 input-group">
    <input type="text" class="form-control cc_input-control" id="id_mobile" 
      aria-describedby="mobilelHelp" placeholder="رقم الموبيل" name="mobile">
    <select id="id_country" class="form-select cc_input-control"
      aria-label="Default select example" name="country">
      <!-- <option selected>Open this select menu</option> -->
      {% for country in countries %}
        <option value="{{ country.id }}" {% if country.id == 63 %}selected{% endif %}>{{country.title}} ({{country.code}}+) </option>
      {% endfor %}
    </select>
    <!-- <div id="mobileHelp" class="form-text">We'll never share your email with anyone else.</div> -->
  </div>

  <div class="mb-3 input-group">
    <input type="text" class="form-control cc_input-control" id="id_first-name"
      aria-describedby="firstNamelHelp" placeholder="الاسم الاول*" name="firstName">
    <input type="text" class="form-control cc_input-control" id="id_last-name"
      aria-describedby="lastNameHelp" placeholder="اسم العائلة*" name="lastName">
    <!-- <div id="firstNamelHelp" class="form-text">We'll never share your email with anyone else.</div> -->
  </div>

  <div class="mb-3">
    <input type="date" class="form-control cc_input-control text-center" id="id_birthdate"
      aria-describedby="birthdateHelp" placeholder="*تاريخ الميلاد" name="birthdate">
    <!-- <div id="birthdateHelp" class="form-text">We'll never share your email with anyone else.</div> -->
  </div>

  <div class="mb-3">
    <input type="password" class="form-control cc_input-control" id="id_password"
      aria-describedby="passwordHelp" placeholder="كلمة المرور*" name="password">
    <!-- <div id="passwordHelp" class="form-text">We'll never share your email with anyone else.</div> -->
  </div>

  <div class="mb-3">
    <input type="password" class="form-control cc_input-control" id="id_confirm"
      aria-describedby="confirmHelp" placeholder="تاكيد كلمة المرور*" name="confirm">
    <!-- <div id="confirmHelp" class="form-text">We'll never share your email with anyone else.</div> -->
  </div>

  <div id="id_regform__last">
    <div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="sex" value="male" id="id_male-radioBox" />
        <label class="form-check-label cc_input-control" for="id_male-radioBox">
          رجل
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="sex" value="female" id="id_female-radioBox"/>
        <label class="form-check-label cc_input-control" for="id_female-radioBox">
          امرأة
        </label>
      </div>
    </div>
    <button type="submit" class="btn btn-success cc_input-label">
      انشاء حساب&nbsp&nbsp&nbsp&nbsp
      <img src="{% static 'scripture/img/user-w.png' %}" alt="Login" style="width: 2rem;"/>
    </button>
  </div>


  
</form>

{% endblock %}

scripture/templates/scripture/shortMessage.html
{% extends 'scripture/layout.html' %}
{% load static %}


{% block content %}
<div id="id_shortmessage">
  <h2 class="text-center shadow-lg p-3 mb-5 bg-body rounded">
      {{shortMessage}}
  </h2>
</div>
{% endblock %}